language: perl
perl:
  - "5.14"
  - "5.14-thr"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.20-thr"
  - "blead"
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
    - perl: 5.18
      env: MOOPS_FUNCTION_PARAMETERS_EVERYWHERE=1
before_install:
  - export DIST_INKT_PROFILE="Dist::Inkt::Profile::TOBYINK"
  - git clone git://github.com/tobyink/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
  - cpan-install "Function::Parameters"
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -lrv $(test-dirs)
after_success:
  - coverage-report
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change
