language: perl
script: HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
install:
  - cpanm -n "indirect" "multidimensional" "bareword::filehandles"
  - cpanm -n "Devel::Pragma" "Exporter::Tiny" "Import::Into" "Kavorka"
  - cpanm -n "Keyword::Simple" "Lexical::Accessor" "Module::Runtime"
  - cpanm -n "Moo" "MooX::late" "MooseX::MungeHas" "Scalar::Util"
  - cpanm -n "Sub::Name" "Test::Fatal" "Test::More" "Test::Requires" "Test::Warnings"
  - cpanm -n "Try::Tiny" "Type::Utils" "Types::XSD::Lite"
  - cpanm -n "namespace::sweep" "true" "Mouse" "Class::Tiny::Antlers"
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"
notifications:
  irc:
    channels:
      - "irc.perl.org#moops"
    on_success: change
