language: perl
script: HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
install:
  - cpanm "Devel::Pragma" "Exporter::Tiny" "Import::Into" "Kavorka" "Keyword::Simple" "Module::Runtime" "Moo" "MooX::late" "MooseX::MungeHas" "Scalar::Util" "Test::Fatal" "Test::More" "Test::Requires" "Try::Tiny" "Type::Utils" "Types::XSD::Lite" "namespace::sweep" "true"
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"
